### ISSUE TITLE
flashing GPT failed

### ISSUE THREAD

**Issue by Oky12** [WoA-project/WoA-Installer#20]
I want to report an error when deploying windows 10 arm64 (See the screenshot below)

![screenshot 225](https://user-images.githubusercontent.com/30838114/52287952-bed8e300-299d-11e9-9dc4-1364fa4b2fb5.png)

after I investigate. I found this (see screenshot below)
![pr](https://user-images.githubusercontent.com/30838114/52288457-d2d11480-299e-11e9-8605-206b732f566d.jpg)

I don't know what caused it.

**Comment by SuperJMN** [comment]
Have you tried to redeploy? Try it. The log contains some strange behavior of the file system

**Comment by Oky12** [comment]
I've tried and the same. the same thing also happens on Windows on Raspberry imager when it flashes to GPT

**Comment by Oky12** [comment]
may mean in the second screenshot. sd card is in conflict with my hdd which is flashed by GPT

**Comment by SuperJMN** [comment]
You mean that you HDD was flashed instead??

**Comment by SuperJMN** [comment]
For what I see, your HDD is Disk 2 and the Micro SD card is Disk 3. Is this right?

**Comment by Oky12** [comment]
I have 2 hdd and 1 ssd

Disk 0 is ssd (system windows) flashed gpt
Disk 1 is hdd flashed mbr
Disk 2 is hdd flashed mbr
Disk 3 is sd card flashed gpt

I think only 1 gpt drive can run on windows

**Comment by SuperJMN** [comment]
Can I reach you via Telegram? Thank you! Please, join our group and write me a private: https://t.me/joinchat/ACWtm01aRdQuRAu1d3kW7Q or write me an e-mail. We need to debug this inside your machine, maybe using TeamViewer.

**Comment by Oky12** [comment]
I have joined the telegram group. maybe we should communicate via email only. because in the group there was a discussion and I did not want to disturb them 😅

Here my email
oki.surianto61@gmail.com

**Comment by Oky12** [comment]
I tried to deploy on Windows 10 MBR and work
![screenshot 226](https://user-images.githubusercontent.com/30838114/52380367-0cd60f80-2aa0-11e9-953c-9653dea6cb14.png)

![screenshot 227](https://user-images.githubusercontent.com/30838114/52380375-13fd1d80-2aa0-11e9-9e38-12aa5e1fe358.png)

**Comment by SuperJMN** [comment]
Strange. It shouldn't have happened. If you don't mind, I'm closing this. Tell me if it happens again.
