### ISSUE TITLE
Can't get to the phone disk

### ISSUE THREAD

**Issue by biconix** [WoA-project/WoA-Installer#21]
I am trying to install Windows 10 on my 950XL
I have used the Windows Phone Internals to unlock the phone. (I think)
However, when I try to install window 10 using the WoA Installer, it tells me that it can't access the phone disk, that I need to place the phone in mass storage mode. 
[screens.pdf](https://github.com/WoA-project/WoA-Installer/files/2846464/screens.pdf)

I must be missing a step, but I can't figure out what it is. Any suggestions?

**Comment by SuperJMN** [comment]
Have you put the phone in Storage Mode?

**Comment by biconix** [comment]
I thought I did. I updated my previous message with screen shots. what step am I leaving out?

**Comment by Veiranx** [comment]
The phone is unlikely to be in mass storage mode. Go to Manual mode under Phone on the left side. There should be an option to reboot into mass storage mode.

**Comment by SuperJMN** [comment]
Please, check this :) https://mspoweruser.com/video-tutorial-for-installing-windows-10-on-arm-on-your-lumia-950-xl/

**Comment by Veiranx** [comment]
Just so it's clear, your phone needs to be unlocked but it doesn't need root access. If the phone's bootloader is currently unlocked, then rebooting to mass storage mode should leave it with a blank screen. WPIntenrals should also recognize it as such.

**Comment by biconix** [comment]
thanks, manually changing it to mass storage worked!
I am configuring Cortana now! 
struggling without a key board. touch doesn't seem to work yet

**Comment by biconix** [comment]
it seems to be working well. but it uses up battery very quickly. it runs hot. I cannot seem to charge it via usb as it drains faster than it charges. I can only charge it via my Qi charger

**Comment by SuperJMN** [comment]
Hey @biconix read this https://www.woaproject.net/viewtopic.php?f=16&t=4 and this https://www.woaproject.net/viewtopic.php?f=16&t=6

**Comment by biconix** [comment]
It is working exactly as described then ??
Thanks, keep up the excellent work
I will make a donation when I get to a computer

____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972( 2) 590-0801

________________________________

**Comment by SuperJMN** [comment]
Big, big thanks @biconix !!! Your donation has been the best news in my day! thank you man!

**Comment by SuperJMN** [comment]
By the way, please, stay tuned, because the new WoA Installer has been renamed to WOA Deployer. Please, find the new project here: https://github.com/WOA-project/WOA-Deployer

The new version is not released yet, but it will be soon :)

**Comment by biconix** [comment]
I will try to keep an eye on it…
Thanks for the hint 😊


_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972(2) 590-0801
