### ISSUE TITLE
Raspberry Pi WoA Installer CLR20r3 crash on Windows 7

### ISSUE THREAD

**Issue by miklosakos** [WOA-Project/WoA-Installer#23]
Whenever I open up Installer.Raspberry.Application.exe it just crashes with CLR20r3 error.
I'm running Windows 7 Home Premium x64.
![kep](https://user-images.githubusercontent.com/8452012/52646786-b4f63900-2ee3-11e9-908b-e8c683e8de31.png)

**Comment by SuperJMN** [comment]
Please, update to Windows 10 (version 1809). The application isn't designed to run in versions prior to W10. Moreover, I encourage you to use the new version of WoA Installer that has been renamed to WOA Deployer. Find it here => https://github.com/WOA-Project/WOA-Deployer

**Comment by SuperJMN** [comment]
BTW, the app fails on startup because your system isn't able to run .NET Framework 4.6.1,l that is the one that uses this app :) 

Time to update!
