### ISSUE TITLE
Doesn't boot

### ISSUE THREAD

**Issue by darkoverlordofdata** [WOA-Project/WoA-Installer#24]
I'm using rpi 3 and Core Package 1.3.0 (with MCCI's USB)

It boots up into the UEFI shell. It was hard to tell what it was, the font is so bad it's hard to read. Once I realized that it was UEFI, I booted into setup and changed the default boot option to Broadcom, saved the setup, and rebooted again, and was finally greeted with the Windows Logo. But after running for about 15 minutes, it went back to the UEFI shell.

**Comment by darkoverlordofdata** [comment]
I've tried booting several times now, and I get different results each time - 

I've got the page with ':( Your PC ran into a problem and needs to restart'
and the following errors:
* page fault in non-paged area
* kernel auto boot invalid lock release
* kmode exception not handled
* attempted execute of non-execute memory

Once it got to 'Choose Your Keyboard Layout' but then it froze.

I get different behavior each time also; sometimes I see the Windows Logo, sometimes just spinning dots. It takes varying length of time. Sometime it displays 'Please Wait' under the logo. But it never does it the same way twice.

I used the exact same hardware with Raspbian, and there were no problems.

**Comment by darkoverlordofdata** [comment]
Oops. Didn't mean to select Close...

**Comment by MartinDavidWaller** [comment]
Hi, I was wondering what minimum size of MicroSD card you would recommend?

Many thanks for any advice you can give.

Martin

**Comment by CornyjK** [comment]
I would recommend 32 GB microSD card as a minimum.

**Comment by MartinDavidWaller** [comment]
Many thanks, I have one on order!

**Comment by pketelaar** [comment]
I am facing same issue. After getting UEFI so it would boot windows it restarted and blue screened multiple times. This morning it’s stuck on choose your keyboard. Pi 3 b + with 32gb Sandisk card, win 10 pro arm and the core package with the mcci usb.

**Comment by SuperJMN** [comment]
Can you please try with build 17134?

Some builds are faulty, it seems. Anyways, I don't think it's an error of the WoA Installer :)
Please, tell me your results.

**Comment by pketelaar** [comment]
Will try. Looks like has to be version 1803 for build 17134

**Comment by darkoverlordofdata** [comment]
32 gb? would be good to put that in the documentation. My rpi comes with a 16 gb sd. Perhaps that is the issue?

**Comment by pketelaar** [comment]
Got it to work with 17134. Is there no Wifi support?

**Comment by MrQueeba** [comment]
Also having the same issue, Windows bluescreens before entering the setup. Pi 3 B

**Comment by ThatWeirdAndrew** [comment]
This is happening to me as well.

**Comment by pketelaar** [comment]
You’ve got to use an older build. I used version 1803 and it worked.

**Comment by darkoverlordofdata** [comment]
it turns out I ran into 2 separate issues. 

* the poor fonts and booting into EFI shell. 
	This was cause by using the 1.3.0 Core Package. I guess that's on me, I always try the latest version. When I fall back to 1.0.0 Core Package, these issues are resolved.

* blue screen errors while booting Windows.
	This is caused by not using the exact parameters shown in https://user-images.githubusercontent.com/3109851/51803240-f5528780-2252-11e9-92e8-2d80169e1131.png
	I changed the language from es to en. When I re-ran using Spanish lanuage, it works. The problem is, I can't read the screen because everthing is in Spanish.

So the technical issues are resolved. It seems the 32 gb 'requirement' is a red herring. Which makes sense - WinRT only uses 16gb on the 32 gb sd chip.

But now there is the cultural issue that this only seems to work in the Spanish version. So, I guess unless you are a Spanish speaker, you can't use this project? That seems pretty lame.

So I suppose I should move this to Telegram? That is not going to happen. I'm not creating a new account with some new startup I've never heard of. Since your project is on github, why aren't you using https://gitter.im/? Or is the purpose of this project to drive traffic to Telegram? I refuse to be part of that.

**Comment by SuperJMN** [comment]
1. If you had to move to Telegram, you wouldn't be writing on this thread.
2. There are LOTS of people running this in other languages, like Chinese, Czech, Portuguese, French, German, Italian... The image you're talking about is just a screenshot with the sample setting. 
3. I use Gitter everyday and it's far, far, worse than Telegram. I invite you to leave your prejudice behind. Telegram simply rocks. The Gitter client for phones is really basic. 
4. Please, change you mood and try to fund your words before writing, especially if you want to accuse people.

**Comment by SuperJMN** [comment]
Please, use woaproject.net for this kind of question. This is only for WoA Installer issues.

**Comment by CornyjK** [comment]
> So the technical issues are resolved. It seems the 32 gb 'requirement' is a red herring. Which makes sense - WinRT only uses 16gb on the 32 gb sd chip.

**Comment by CornyjK** [comment]
> So I suppose I should move this to Telegram? That is not going to happen. I'm not creating a new account with some new startup I've never heard of. Since your project is on github, why aren't you using https://gitter.im/? Or is the purpose of this project to drive traffic to Telegram? I refuse to be part of that.

We do not force you to be part of us, just don't be...

> So the technical issues are resolved. It seems the 32 gb 'requirement' is a red herring. Which makes sense - WinRT only uses 16gb on the 32 gb sd chip.

Windows RT should be smaller, but even if it isn't, you want to have some space for doing stuff (if you are not one of those people who just want see that it works, if you are, it works, you don't have to try).

> But now there is the cultural issue that this only seems to work in the Spanish version. So, I guess unless you are a Spanish speaker, you can't use this project? That seems pretty lame.

wtf? It works in English as every other language, screenshot is in Spanish because the man taking it is Spanish.

@darkoverlordofdata, please do not make any more comments on @WOA-Project repositories, I will not react to them and @SuperJMN probably either.

> Got it to work with 17134. Is there no Wifi support?

Please check [status matrix](https://discourse.pi64.win/t/status-of-the-arm64-device-drivers-as-of-12-feb-2019/38).
