### ISSUE TITLE
Replace RG-Adguard.net with https://uupdump.ml/

### ISSUE THREAD

**Issue by gjsman** [WOA-Project/WoA-Installer#25]
The website RG-adguard.net looks _generally fishy_ to new visitors, and it isn't clear where the binaries are downloaded from (e.g. piracy). I actually had a real argument with someone on the Raspberry Pi Forum who took one look at the RG-adguard.net site and thought we were doing piracy.

https://uupdump.ml/ is a similar website, but is easier to use, clear on where the files are downloaded from, no ads, and overall safer-looking. And not from Russia.

**Comment by CornyjK** [comment]
I prefer current one, your arguments seem to be pointless, but José will decide.

**Comment by gjsman** [comment]
I actually @CornyjK had a real argument with somebody on the RPF Forum who concluded that the current rg-adguard.net looked a _lot_ like piracy. I could hardly convince him otherwise.

**Comment by Atavic** [comment]
> looks fishy

So help the admins with a better template for the site. Out of irony, *tb.rg-adguard.net/public.php* gets the .iso files directly from MS Techbench Servers and even Windows Insider MVPs at *answers.microsoft.com* suggest and use the adguard site.

If you dare starting a download there, you'll see that the .iso comes from *software-download.microsoft.com/some-text-here*. 
Adguard is an interface to MS downlaod servers.

**Comment by Atavic** [comment]
> It looks fishy

So help the admins with a better template for the site.
Out of irony, *tb.rg-adguard.net/public.php* gets the .iso files directly from MS Techbench Servers and even Windows Insider MVPs at *answers.microsoft.com* suggest and use the adguard site.

If you dare starting a download there, you'll see that the .iso file comes from *software-download.microsoft.com/*

Adguard is an interface to MS download servers.

**Comment by DrFrankReade** [comment]
Yeah and download it with a "downloader" exe file from uupdump- Yeah really not fishy at all.

**Comment by gjsman** [comment]
@Atavic If you look at UUP Dump, it does the same.

@DrFrankReade Actually, RG-Adguard says to use a CMD file you downloaded. UUP Dump uses Aria2 for downloading, which is an open-source project on GitHub.

**Comment by SuperJMN** [comment]
We can use both. Better to have more than 1 option.

**Comment by CornyjK** [comment]
@SuperJMN 
That is master domain of https://uup.rg-adguard.net/ subdomain. IMHO people that are against Russian stuff are just stupid, what is actually bad on Russian stuff? Is it that Americans say it is bad (Kaspersky, etc.)? https://uup.rg-adguard.net/ served us for a long time and we are glad for that.

**Comment by Atavic** [comment]
@SuperJMN [TechBench by WZT](https://tb.rg-adguard.net/public.php) has a language option on top right.
