### ISSUE TITLE
Windows on Arm Installer Sd Card Flash Issue : Method Not Found

### ISSUE THREAD

**Issue by iamnotagentleman** [WOA-Project/WoA-Installer#26]
when try windows 10 arm64 flash to sdcard :  display log Method not found : 'system.runtime.interopservices.architectureInstaller.Core.Services.Wim.DiskImageMetaData.get_Architecture()' 
Screenshots:
https://ibb.co/t8JL28w
https://ibb.co/Jd0J6fh
log file: [20190213.txt](https://github.com/WOA-Project/WoA-Installer/files/2861855/20190213.txt)

Solved : install .NET Framework

**Comment by SuperJMN** [comment]
Which Windows 10 version do you have? This app requires .NET Framework 4.6.1.
