### ISSUE TITLE
Error: The term "Get-Disk" is not recognized

### ISSUE THREAD

**Issue by snawolf** [WOA-Project/WoA-Installer#32]
Drive Selection does not work. Opening the Installer results in the above error message. No disk drives can be found to use for writing to the SD Card because of the Get-Disk error.
![error 2](https://user-images.githubusercontent.com/7643595/52754741-9785b400-3036-11e9-99a8-fe0ff7e9fa36.jpg)

**Comment by SuperJMN** [comment]
Hello! Which Windows version are you running? My application requires a recent version of Windows 10.

**Comment by snawolf** [comment]
It would have helped if you had mentioned the double-secret hidden "Windows 10 only" requirement in your installation guide. Or is this part of your "Super easy to use. No-hassle. All you need is here. Buy me a beer" technique of providing instructions, which I carefully followed? 

Anyhow, thank you for your prompt reply and assistance in explaining why I got an error while following your instructions. I sincerely do appreciate the work you have done. Everything else worked great,

**Comment by SuperJMN** [comment]
Firstly, this project is done in my free time. Secondly, you came here looking for answers and you got answers. Why are you even complaining?

I've added the Windows 10 only requirement that I missed somewhat. 

Please, don't be an asshole and just take the fucking goodness I'm providing FOR FREE. If you're here to cry, go away. 

BTW, I don't like beer.
