### ISSUE TITLE
About office on woa

### ISSUE THREAD

**Issue by Askmewho** [WOA-Project/WoA-Installer#33]
Hii! This its not a report of a bug but still I need some info or help about this topic. I have some doubts about how its the actual state of woa. The msoffice implementation of office its still on emulation?If the answer is yes, it use a 32 bit arm msoffice or 64bit arm build instead? I ask these thing because i want to use microsoft office app under wine natively. I need, if it possible, a few advices of how to extract the binary to run it on linux, if its compiled to arm 32 bits... i search a lot time ago inside a windows rt image and i could find microsoft offfice rt version... and if there its a 32 bit arm office it would be great than we could launch it natively out of the box on linux distro. Iva compiled wine several times on my pi 3, just for test the notaz recompiled binaries of diablo II, starcraft, etc. But the only program i could execute from other source its rufus... and it didnt work properly because its really windows api demanding. The same happend on x86 system, so for me was a succes. If you wanna help i would be extremly greatful with you. Thanks anyway.

**Comment by moliata** [comment]
For questions, please ask them at https://t.me/raspberrypiwoa
