### ISSUE TITLE
Core Package Raspberry Pi does not exist anymore

### ISSUE THREAD

**Issue by nmaas87** [WOA-Project/WoA-Installer#34]
As stated above, the link does only led to a OneDrive site which tells that the file does not exist anymore

**Comment by CornyjK** [comment]
Not sure which link are you using, but https://onedrive.live.com/?authkey=%21AAg1P7lDOqOnZ9g&id=C8B0DBB75540E8D5%211189489&cid=C8B0DBB75540E8D5 works just fine.

**Comment by nmaas87** [comment]
It does work as soon as you're using an icognicto tab / are not logged in OneDrive. I could not see the files when I was logged onto my OneDrive account, for people which encounter the same problem

**Comment by CornyjK** [comment]
![image](https://user-images.githubusercontent.com/9021297/52777546-5d231380-3044-11e9-9759-afada872b43b.png)
Well, I can't see an issue here.

**Comment by CornyjK** [comment]
OneDrive bugs sometimes, that is a known fact.

**Comment by Fabrimagic1** [comment]
help please,when i put the file core package.rar in "windows on arm installer" it say that file :file/cores doesn't exist
